### PR TITLE
Fix webpack 4 deprecation warnings

### PR DESCRIPTION
**Pull request by jdachtera**
This pull request converts the event listeners to the new hooks api introduced in Webpack 4.

### CODE REVIEW

**Comment by wuct** [comment]
Thanks!

**Comment by wuct** [comment]
Please don't update the version number, I'll do it before releasing. Also, I'll need to update the test.

**Comment by jdachtera** [comment]
No problem, I can also have a look at the test. Sorry I missed that :)
I think it should be a new major version bump though because this won't work with webpack 3 anymore.

**Comment by jdachtera** [comment]
The test is fixed. I updated the webpack dependency to version 4. 
Needed to add the --testEnvironment=node flag to the jest command because I ran into this problem: https://github.com/mxmul/closure-loader/pull/40
Let me know if you need anything else.

**Comment by jdachtera** [comment]
Any chance of getting this merged?

**Comment by wuct** [comment]
Thanks a lot! I am traveling right now, and I’ll try to find some time to release it these days.

**Comment by wuct** [comment]
Landing at 1.0.0

**Pull request merged**
